### PR TITLE
Switch to using SCION-specific checksum.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-lwip/12)

### CODE REVIEW

**Comment by pszal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/scion/scion.c, line 147 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12#-KjrwlwGdZ7aEhr9zes-:-KjrwlwGdZ7aEhr9zes0:bgrjhuu) ([raw file](https://github.com/netsec-ethz/scion-lwip/blob/29e984a16138209ba94249c97d750d9bfaddeaba/src/core/scion/scion.c#L147)):*
> ```C
>        u8_t proto, u16_t proto_len)
> {
>     int chk_count = 6; // Dst IA, Src IA, Dst host, Src host, L4 proto, L4 len
> ```

why not a single chunk for the address block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12)*

**Comment by pszal** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12#-:-Kjrwr9rs0FbHYCZGUQx:bnfp4nl)*

**Comment by kormat** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/scion/scion.c, line 147 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12#-KjrwlwGdZ7aEhr9zes-:-Kjrxc4MCz-ftiDZlqDd:bjrzpe) ([raw file](https://github.com/netsec-ethz/scion-lwip/blob/29e984a16138209ba94249c97d750d9bfaddeaba/src/core/scion/scion.c#L147)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

why not a single chunk for the address block?
</blockquote></details>

I couldn't see a way to access that directly. How do i go about it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12#-:-KjryNzbM5tZTmLao83J:bnfp4nl)*

**Comment by pszal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/scion/scion.c, line 147 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12#-KjrwlwGdZ7aEhr9zes-:-Kjry1C-PcOOHLdMDKzY:b-9443m7) ([raw file](https://github.com/netsec-ethz/scion-lwip/blob/29e984a16138209ba94249c97d750d9bfaddeaba/src/core/scion/scion.c#L147)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I couldn't see a way to access that directly. How do i go about it?
</blockquote></details>

oh, right, nvmd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip/12)*

**Pull request merged**
